### ISSUE TITLE
[BUG] Extremely unreliable behavior

### ISSUE THREAD

**Issue by TheKombiZombi** [Gerark/just-popcorn-initiative#1] opened 2023-09-03 18:38 UTC
Preface: I have never written a bug report in my life nor is my intelligence high enough to make sense of things, so bear with me.

**Module Version:** v1.0.2

**Describe the bug**
When I first wanted to test this module, I used the starter heroes and two zombies and an oger zombie in the same scene. The zombies share the same actor, but are separate tokens. Whenever I started combat and tried choosing the next actor, the list would be completely empty. This is not the case if only the player characters are active combatants.
In a world with only this module and my own module containing monsters and such, the behavior is the same.
For some reason, changing the permissions of the monsters to "limited" for the players added them to the choose actor screen.
Additional behaviors I found included:
- Deleted actors (and tokens) still appearing in the selection screen
- Hovering over any token (especially the actors as seen in the screenshot) provides a warning stating "Popcorn Initiative - Can't find the token. The provided token id is invalid.

**To Reproduce**
1. Open a world and have a scene with an encounter
2. Only mark actor tokens as active combatants begin combat, end turn, and choose next combatant.
3. Works as expected
4. End combat
5. Drag a new monster from the compendium into the actors tab
6. Drag said monster onto the canvas
7. Mark all tokens as active combatants, begin combat, end turn, and see that the selection screen is devoid of all combatants
8. Unable to end turn, therefore unable to play

**Expected behavior**
I expected to be able to see all active combatants of the current encounter, regardless of permissions, and choose any option.

**Screenshots**
![Foundry_Virtual_Tabletop_PDepTy1P3s](https://github.com/Gerark/just-popcorn-initiative/assets/107818521/4ae68077-e599-4ff9-99e8-83acae20c8ce)
This is a screenshot from a world with only this module and my own (just actors and items). As seen, "Der Wächter" is not in the selection screen despite being in the combat tracker and an active combatant. I hovered over the actors in the selection screen and the warning at the top kept being displayed.

**Browser:**
 Foundry itself

**Foundry Version:** 
Version 11 Stable, Build 308

**Game System:** 
DnD5e - 2.3.1

**Comment by Gerark** [comment] 2023-09-04 04:13
Oh no, my first bug for this module. I'll try to look at it asap. 
I'll try to reproduce this on my own and come to you as soon as I'm able to find at least the issue behind ( so you know I'm on it ).

I have a couple of questions:
- When you say "The zombies share the same actor, but are separate tokens" what that actually means. I do remember I did some tests where the same actor can be in a fight with multiple tokens and that seemed to work as expected. But maybe this is a different case

- Have you changed the permissions while the Selection Window was shown or before that?

- How do you delete the actors? Do you remove them entirely from the game or just from the combat tracker?

**Comment by Gerark** [comment] 2023-09-04 04:32
Also, could you share with me the world you tested? Maybe it will be easier to spot the issue by doing so.

**Comment by Gerark** [comment] 2023-09-04 04:41
I also tried to follow the Repro steps unfortunately without success. As you can see the Dragon in my case is showing up in the Selection Screen.

![image](https://github.com/Gerark/just-popcorn-initiative/assets/7666672/082b1777-f468-43d8-9235-63e96102ce9f)

**Comment by TheKombiZombi** [comment] 2023-09-04 16:45
After encountering some more inconsistencies, I have at least 3 (more or less) consistent ways of breaking the module. I'll include a 5 minute long video of me showcasing it while rolling natural 1s on my speek checks. Anyway, I also want to mention that for some reason Foundry doesn't give any warnings that your module has socketlib as a dependency.

In case you don't want to hear my ramblings and just want the text reproduction and the world:

Consistent Bug:
1. Start combat.
2. Delete the NPC token from the scene.
3. End combat.
4. Create an NPC token from another monster by dragging it on the scene.
5. Start combat as normal
6. The module will list the deleted monster in the "previous actors" section and repeatedly display the warning message as it can be seen in my initial post. Additionally, selecting another actor to begin their turn doesn't work, completely breaking the module.

Kinda Consistent Bug:
1. Start combat.
2. Leave the world by using "Return to Setup" without ending the combat.
3. Load the world.
4. Go to the combat tracker and click next turn.
5. Sometimes the actor selection screen is completely empty

Extremely Cursed World Bug:
Not actually reproducable, because the empty actor selection screen is the default way the module works in that world. The world uses around 60 modules, and I have repeatedly disabled and enabled them and nothing I do seemed to fix it, besides the permissions. I think it's just the world being broken to some degree.

Foundry Error Messages from the Console:
```
ModuleUtils.js:154
Uncaught TypeError: Cannot read properties of undefined (reading 'isGM')
    at ModuleUtils.retrieveOwnersInfo (ModuleUtils.js:154:53)
    at StoreUpdater._updateSelectableCombatants (StoreUpdater.js:205:41)
    at StoreUpdater.js:24:22
```

```
foundry.js:21481
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'combatantId')
    at Combat._manageTurnEvents (foundry.js:21481:53)
    at Combat._onCreate (foundry.js:21319:10)
    at ClientDatabaseBackend.callback (foundry.js:13525:11)
    at foundry.js:13498:43
    at Array.map (<anonymous>)
    at #handleCreateDocuments (foundry.js:13498:33)
```
Since the file size of the video is too large for Github, I will link it as an unlisted youtube video: https://www.youtube.com/watch?v=HsGShqbsEn4. Might take some time for it to become available.

And here's the world which only uses my module, socketlib, and popcorn initiative.
[lock-test.zip](https://github.com/Gerark/just-popcorn-initiative/files/12515377/lock-test.zip)

**Comment by Gerark** [comment] 2023-09-04 17:13
Thank you for the information. It's very helpful! It appears that some old users have been assigned to some of those actors, but those users no longer exist.

When I try to retrieve the owner of the actors, I go through all the users with enough permissions, and I had been assuming that all the users are still valid. However, it seems that Foundry doesn't clean up permissions for users who no longer exist, and the GM can't change the permissions because those users are no longer in the system.

I'll look for a fix related to this issue (which should be fairly easy), hoping it will resolve the problem in the world you provided ( at least one of the issues ). In the meantime, if you're reading this message, could you confirm if something like that has happened, such as changing or removing users?

**Comment by Gerark** [comment] 2023-09-04 17:33
DIdn't mean to close the issue actually. I'm publishing a new version v1.0.3 containing the potential fix very soon.

**Comment by TheKombiZombi** [comment] 2023-09-05 14:47
> In the meantime, if you're reading this message, could you confirm if something like that has happened, such as changing or removing users?

If I remember correctly, I have changed the users for the world I sent before activating the module by adding another user to test from the players' POV (I tested two other modules before the initiative module).

**Closed** 2023-09-05 14:55 UTC
Labels: bug
